PunktDe:
  Sentry:
    Flow:
      dsn: '%env:SENTRY_DSN%'
      environment: '%env:SENTRY_ENVIRONMENT%'
Neos:
  Flow:
    error:
      exceptionHandler:
        className: PunktDe\Sentry\Flow\Handler\ProductionExceptionHandler
